name: weatherapi_gse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  go_router: ^17.0.0

dev_dependencies:
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    

flavorizr:
  flavors:
    dev:
      app:
        name: "Weather App Dev"
      android:
        applicationId: "com.miguelamolina.wheatherapp.dev"
      ios:
        bundleId: "com.miguelamolina.wheatherapp.dev"
      assets:
        - assets/dev/
        - .env

    prod:
      app:
        name: "Weather App"
      android:
        applicationId: "com.miguelamolina.wheatherapp"
      ios:
        bundleId: "com.miguelamolina.wheatherapp"
      assets:
        - assets/prod/
        - .env
