name: weatherapi_gse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localization: ^0.3.3
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.9
  geolocator: ^14.0.2
  go_router: ^17.0.0
  google_geocoding: ^0.2.0
  google_maps_flutter: ^2.14.0
  icons_launcher: ^3.0.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  drift_dev: ^2.29.0
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/prod/

flavorizr:
  flavors:
    dev:
      app:
        name: "Weather App Dev"
      android:
        applicationId: "com.miguelamolina.wheatherapp.dev"
      ios:
        bundleId: "com.miguelamolina.wheatherapp.dev"
      assetsUrl:
        - assets/dev/
        - .env

    prod:
      app:
        name: "Weather App"
      android:
        applicationId: "com.miguelamolina.wheatherapp"
      ios:
        bundleId: "com.miguelamolina.wheatherapp"
      assetsUrl:
        - assets/prod/
        - .env
